site_name: django-ulidfield
repo_url: https://github.com/dumaas/django-ulidfield
site_url: https://django-ulidfield.readthedocs.io
theme:
  name: readthedocs

nav:
  - Home: index.md

markdown_extensions:
  - toc:
      permalink: true
