name: Test

on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/build

    - name: Unit test
      run: poetry run pytest -v
